// Generates the Supabase DDL from lib/data/sync/sync_tables.dart.
//
// Run:  dart run tool/generate_supabase_sql.dart > docs/supabase_migration.sql
//
// The point is that the schema is derived, not transcribed. Hand-written SQL
// drifted from the app's real needs for months — the push kept trying to
// upload columns Postgres did not have, PostgREST rejected the whole row, and
// the failure was invisible because the queue just retried forever.
import 'package:fitpilot/data/sync/sync_tables.dart';

void main() {
  final b = StringBuffer();

  b.writeln('-- FitPilot — Supabase schema');
  b.writeln('-- GENERATED by tool/generate_supabase_sql.dart. Do not hand-edit:');
  b.writeln('-- regenerate after changing lib/data/sync/sync_tables.dart.');
  b.writeln('--');
  b.writeln('-- Safe to re-run. Creates what is missing, adds columns that are');
  b.writeln('-- absent, and never drops a table or a column that holds data.');
  b.writeln();

  for (final spec in kSyncTables) {
    final t = spec.remote;
    final rule = '-- ${'=' * 66}';
    b.writeln(rule);
    b.writeln('-- $t');
    b.writeln(rule);
    b.writeln();

    // CREATE with only the structural columns, then ALTER the rest in. That
    // way a table that already exists (with an older shape) is upgraded by the
    // same script that creates a new one — no DROP, no data loss.
    b.writeln('CREATE TABLE IF NOT EXISTS $t (');
    if (spec.singleton) {
      // One row per account, so the user's uuid IS the primary key.
      b.writeln('  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,');
      b.writeln('  user_id uuid,');
    } else {
      b.writeln('  id text PRIMARY KEY,');
      b.writeln(
        '  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,',
      );
    }
    b.writeln('  updated_at timestamptz NOT NULL DEFAULT now()');
    b.writeln(');');
    b.writeln();

    // Columns, each guarded so re-running is a no-op.
    b.writeln('DO \$\$ BEGIN');
    for (final c in spec.columns) {
      b.writeln(
        '  BEGIN ALTER TABLE $t ADD COLUMN ${c.name} ${c.pgType}; '
        'EXCEPTION WHEN duplicate_column THEN NULL; END;',
      );
    }
    // `deleted` is how a push tombstones a row. The pull reads it to delete
    // locally, so every synced table needs it even though no spec lists it.
    b.writeln(
      '  BEGIN ALTER TABLE $t ADD COLUMN deleted boolean NOT NULL DEFAULT false; '
      'EXCEPTION WHEN duplicate_column THEN NULL; END;',
    );
    // user_id and updated_at come from the CREATE above — but only when this
    // run actually created the table. A table left over from an older schema
    // skips the CREATE entirely (IF NOT EXISTS), so these have to be added
    // here too. Without it the index below fails with 42703: column
    // "user_id" does not exist, which is exactly what happened on the first
    // attempt at this migration.
    b.writeln(
      '  BEGIN ALTER TABLE $t ADD COLUMN user_id uuid; '
      'EXCEPTION WHEN duplicate_column THEN NULL; END;',
    );
    b.writeln(
      '  BEGIN ALTER TABLE $t ADD COLUMN updated_at timestamptz '
      'NOT NULL DEFAULT now(); '
      'EXCEPTION WHEN duplicate_column THEN NULL; END;',
    );
    b.writeln('END \$\$;');
    b.writeln();

    // Backfill user_id on rows that predate the column, then make it usable.
    // A legacy row with a NULL owner is invisible under RLS, so it would look
    // like the user's data had vanished.
    if (spec.singleton) {
      b.writeln('-- A singleton row is keyed by the owner, so id IS user_id.');
      b.writeln('UPDATE $t SET user_id = id WHERE user_id IS NULL;');
      b.writeln();
    }

    // The app writes rows during onboarding with most fields still empty, so
    // any legacy NOT NULL has to come off or the upsert is rejected.
    b.writeln('-- Drop legacy NOT NULLs: the app saves partial rows during');
    b.writeln('-- onboarding and would otherwise be rejected.');
    b.writeln('DO \$\$');
    b.writeln('DECLARE col record;');
    b.writeln('BEGIN');
    b.writeln('  FOR col IN');
    b.writeln('    SELECT column_name FROM information_schema.columns');
    b.writeln("    WHERE table_schema = 'public' AND table_name = '$t'");
    b.writeln("      AND is_nullable = 'NO'");
    b.writeln("      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')");
    b.writeln('  LOOP');
    b.writeln(
      '    EXECUTE format(\'ALTER TABLE $t ALTER COLUMN %I DROP NOT NULL\', col.column_name);',
    );
    b.writeln('  END LOOP;');
    b.writeln('END \$\$;');
    b.writeln();

    if (!spec.singleton) {
      b.writeln(
        'CREATE INDEX IF NOT EXISTS idx_${t}_user ON $t (user_id);',
      );
    }
    b.writeln(
      'CREATE INDEX IF NOT EXISTS idx_${t}_updated ON $t (updated_at);',
    );

    // weight_entries upserts on (user_id, for_date): one weigh-in per day.
    if (spec.local == 'weight_entries') {
      b.writeln();
      b.writeln('-- The push upserts on this pair, so it must be unique.');
      b.writeln('DO \$\$ BEGIN');
      b.writeln('  ALTER TABLE $t ADD CONSTRAINT ${t}_user_date_key');
      b.writeln('    UNIQUE (user_id, for_date);');
      b.writeln('EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END \$\$;');
    }
    b.writeln();

    // RLS. Without it every user reads every other user's rows.
    b.writeln('ALTER TABLE $t ENABLE ROW LEVEL SECURITY;');
    final ownCol = spec.singleton ? 'id' : 'user_id';
    b.writeln('DROP POLICY IF EXISTS "own_$t" ON $t;');
    b.writeln('CREATE POLICY "own_$t" ON $t');
    b.writeln('  FOR ALL USING (auth.uid() = $ownCol)');
    b.writeln('  WITH CHECK (auth.uid() = $ownCol);');
    b.writeln();
  }

  // Verification.
  final rule = '-- ${'=' * 66}';
  b.writeln(rule);
  b.writeln('-- Verify: every synced table should appear, with rls_enabled = true.');
  b.writeln(rule);
  b.writeln('SELECT c.relname AS table_name, c.relrowsecurity AS rls_enabled');
  b.writeln('FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace');
  b.writeln("WHERE n.nspname = 'public' AND c.relname IN (");
  b.writeln(kSyncTables.map((s) => "  '${s.remote}'").join(',\n'));
  b.writeln(') ORDER BY c.relname;');

  // ignore: avoid_print
  print(b.toString());
}
