import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:fitpilot/application/providers/food_manifest_provider.dart';
import 'package:fitpilot/core/theme/app_theme.dart';
import 'package:fitpilot/core/ui/app_card.dart';
import 'package:fitpilot/core/ui/food_image.dart';

/// Attribution for the bundled food photos.
///
/// This screen exists for a legal reason, not a decorative one: the photos come
/// from Wikimedia Commons under Creative Commons licences that require naming
/// the photographer and the licence. Those two facts used to be rendered bare —
/// a username like "Nerd271" and a code like "CC BY-SA 3.0" with nothing to say
/// what either was — which read as random noise. Everything here is now
/// labelled, explained, and links back to the original.
///
/// The list is generated by `tool/fetch_food_images.mjs` from the live Wikimedia
/// API. It is never hand-written, so it always matches what actually shipped.
class ImageCreditsScreen extends ConsumerStatefulWidget {
  const ImageCreditsScreen({super.key});

  @override
  ConsumerState<ImageCreditsScreen> createState() => _ImageCreditsScreenState();
}

class _ImageCreditsScreenState extends ConsumerState<ImageCreditsScreen> {
  String _query = '';

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final creditsAsync = ref.watch(imageCreditsProvider);

    return Scaffold(
      backgroundColor: theme.colorScheme.surface,
      appBar: AppBar(
        title: const Text('Photo credits'),
        backgroundColor: theme.colorScheme.surface,
        foregroundColor: theme.colorScheme.onSurface,
        elevation: 0,
      ),
      body: creditsAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(
          child: Text('Could not load credits', style: theme.textTheme.body),
        ),
        data: (credits) {
          if (credits.isEmpty) {
            return Center(
              child: Text('No bundled photos yet.', style: theme.textTheme.body),
            );
          }

          final visible = _query.isEmpty
              ? credits
              : credits
                    .where(
                      (c) =>
                          c.imageKey.toLowerCase().contains(_query) ||
                          c.author.toLowerCase().contains(_query),
                    )
                    .toList();

          return ListView(
            padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
            children: [
              const _WhyCard(),
              const SizedBox(height: 14),
              _SearchField(
                onChanged: (v) => setState(() => _query = v.toLowerCase().trim()),
                count: credits.length,
              ),
              const SizedBox(height: 14),
              if (visible.isEmpty)
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 40),
                  child: Center(
                    child: Text(
                      'No photos match "$_query".',
                      style: theme.textTheme.caption,
                    ),
                  ),
                )
              else
                for (final credit in visible)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 10),
                    child: _CreditTile(credit: credit),
                  ),
            ],
          );
        },
      ),
    );
  }
}

class _WhyCard extends StatelessWidget {
  const _WhyCard();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final ext = theme.extension<AppColors>()!;

    return AppCard(
      padding: const EdgeInsets.all(18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(
                Icons.photo_camera_outlined,
                size: 19,
                color: theme.colorScheme.primary,
              ),
              const SizedBox(width: 9),
              Text('Thanks to these photographers', style: theme.textTheme.h2),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            'The food photos in FitPilot come from Wikimedia Commons. Their '
            'licences let us use them for free, on the condition that we name '
            'the photographer and the licence — which is what this page is for.',
            style: theme.textTheme.caption,
          ),
          const SizedBox(height: 10),
          Row(
            children: [
              Icon(Icons.open_in_new_rounded, size: 13, color: ext.textDisabled),
              const SizedBox(width: 6),
              Expanded(
                child: Text(
                  'Tap any photo to see the original.',
                  style: theme.textTheme.caption.copyWith(
                    color: ext.textDisabled,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _SearchField extends StatelessWidget {
  final ValueChanged<String> onChanged;
  final int count;

  const _SearchField({required this.onChanged, required this.count});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final ext = theme.extension<AppColors>()!;

    return Container(
      decoration: BoxDecoration(
        color: ext.surfaceRaised,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: ext.hairline),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 14),
      child: Row(
        children: [
          Icon(Icons.search_rounded, size: 19, color: ext.textDisabled),
          const SizedBox(width: 10),
          Expanded(
            child: TextField(
              onChanged: onChanged,
              style: theme.textTheme.body,
              cursorColor: theme.colorScheme.primary,
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: 'Search $count photos or photographers',
                hintStyle: theme.textTheme.caption.copyWith(
                  color: ext.textDisabled,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _CreditTile extends StatelessWidget {
  final ImageCredit credit;

  const _CreditTile({required this.credit});

  Future<void> _openSource(BuildContext context) async {
    if (credit.source.isEmpty) return;
    final uri = Uri.tryParse(credit.source);
    if (uri == null) return;
    // Best-effort: a device with no browser must not crash the screen.
    try {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (_) {}
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final ext = theme.extension<AppColors>()!;

    return AppCard(
      padding: const EdgeInsets.all(12),
      onTap: credit.source.isEmpty ? null : () => _openSource(context),
      child: Row(
        children: [
          FoodImage(
            name: credit.imageKey,
            imageKey: credit.imageKey,
            size: 52,
            radius: 12,
          ),
          const SizedBox(width: 13),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  _titleFor(credit.imageKey),
                  style: theme.textTheme.bodyStrong,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 3),
                // Labelled explicitly. A bare username reads as noise; "Photo
                // by Nerd271" reads as a credit.
                Text(
                  credit.isPublicDomain
                      ? 'Public domain — no attribution required'
                      : 'Photo by ${credit.author}',
                  style: theme.textTheme.caption,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 6),
                _LicenceChip(license: credit.license),
              ],
            ),
          ),
          if (credit.source.isNotEmpty)
            Icon(Icons.open_in_new_rounded, size: 16, color: ext.textDisabled),
        ],
      ),
    );
  }

  /// `gulab_jamun` → `Gulab jamun`
  static String _titleFor(String imageKey) {
    final words = imageKey.replaceAll('_', ' ');
    if (words.isEmpty) return words;
    return words[0].toUpperCase() + words.substring(1);
  }
}

/// The licence, prefixed so the code is recognisable as a licence rather than
/// looking like a stray product number.
class _LicenceChip extends StatelessWidget {
  final String license;

  const _LicenceChip({required this.license});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final ext = theme.extension<AppColors>()!;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: ext.surfaceRaised,
        borderRadius: BorderRadius.circular(6),
        border: Border.all(color: ext.hairline),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.balance_rounded, size: 11, color: ext.textDisabled),
          const SizedBox(width: 5),
          Text(
            'Licence: $license',
            style: theme.textTheme.overline.copyWith(color: ext.textDisabled),
          ),
        ],
      ),
    );
  }
}
