import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:fitpilot/application/providers/food_manifest_provider.dart';
import 'package:fitpilot/core/theme/app_theme.dart';
import 'package:fitpilot/core/ui/food_image.dart';

/// Attribution for the bundled food photos.
///
/// Most are Creative Commons licensed, which requires crediting the author. The
/// list is generated by `tool/fetch_food_images.mjs` from the live Wikimedia
/// API — it is never hand-written, so it always matches what actually shipped.
class ImageCreditsScreen extends ConsumerWidget {
  const ImageCreditsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final ext = theme.extension<AppColors>()!;
    final creditsAsync = ref.watch(imageCreditsProvider);

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        title: const Text('Image credits'),
        backgroundColor: theme.colorScheme.surface,
        foregroundColor: theme.colorScheme.onSurface,
      ),
      body: creditsAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(
          child: Text('Could not load credits', style: theme.textTheme.body),
        ),
        data: (credits) {
          if (credits.isEmpty) {
            return Center(
              child: Text(
                'No bundled photos yet.',
                style: theme.textTheme.body,
              ),
            );
          }
          return ListView.separated(
            padding: const EdgeInsets.all(16),
            itemCount: credits.length + 1,
            separatorBuilder: (_, _) => Divider(
              color: theme.dividerColor,
              height: 1,
            ),
            itemBuilder: (context, index) {
              if (index == 0) {
                return Padding(
                  padding: const EdgeInsets.only(bottom: 16),
                  child: Text(
                    'Food photos come from Wikimedia Commons under the '
                    'licenses listed below. Thanks to the photographers who '
                    'made them free to use.',
                    style: theme.textTheme.caption,
                  ),
                );
              }

              final credit = credits[index - 1];
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Row(
                  children: [
                    FoodImage(
                      name: credit.imageKey,
                      imageKey: credit.imageKey,
                      size: 48,
                      radius: 10,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            _titleFor(credit.imageKey),
                            style: theme.textTheme.bodyStrong,
                          ),
                          const SizedBox(height: 2),
                          Text(
                            credit.displayAuthor,
                            style: theme.textTheme.caption,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 8),
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: BoxDecoration(
                        color: ext.surfaceRaised,
                        borderRadius: BorderRadius.circular(999),
                      ),
                      child: Text(
                        credit.license,
                        style: theme.textTheme.caption,
                      ),
                    ),
                  ],
                ),
              );
            },
          );
        },
      ),
    );
  }

  /// `gulab_jamun` → `Gulab jamun`
  String _titleFor(String imageKey) {
    final words = imageKey.replaceAll('_', ' ');
    if (words.isEmpty) return words;
    return words[0].toUpperCase() + words.substring(1);
  }
}
