-- FitPilot — Supabase schema
-- GENERATED by tool/generate_supabase_sql.dart. Do not hand-edit:
-- regenerate after changing lib/data/sync/sync_tables.dart.
--
-- Safe to re-run. Creates what is missing, adds columns that are
-- absent, and never drops a table or a column that holds data.

-- ==================================================================
-- profiles
-- ==================================================================

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  user_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE profiles ADD COLUMN name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN avatar_url text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN goal_weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN height_cm real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN age integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN gender text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN goal text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN activity_level text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN allowance_kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN target_override integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN equipment text[]; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN theme_mode text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN theme_color text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN plan_category_pref text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN plan_pace_pref text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN unit_kg_lb text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN week_starts_mon boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN haptics_on boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_week integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_day integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN onboarding_complete boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- A singleton row is keyed by the owner, so id IS user_id.
UPDATE profiles SET user_id = id WHERE user_id IS NULL;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE profiles ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_profiles_updated ON profiles (updated_at);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_profiles" ON profiles;
CREATE POLICY "own_profiles" ON profiles
  FOR ALL USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ==================================================================
-- food_logs
-- ==================================================================

CREATE TABLE IF NOT EXISTS food_logs (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE food_logs ADD COLUMN food_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN food_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN custom_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN quantity real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN kcal_min integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN kcal_max integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN source text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN logged_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN deleted_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'food_logs'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE food_logs ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_food_logs_user ON food_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_food_logs_updated ON food_logs (updated_at);

ALTER TABLE food_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_food_logs" ON food_logs;
CREATE POLICY "own_food_logs" ON food_logs
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- burn_completions
-- ==================================================================

CREATE TABLE IF NOT EXISTS burn_completions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE burn_completions ADD COLUMN for_date text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN activity text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN minutes integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN completed_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'burn_completions'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE burn_completions ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_burn_completions_user ON burn_completions (user_id);
CREATE INDEX IF NOT EXISTS idx_burn_completions_updated ON burn_completions (updated_at);

ALTER TABLE burn_completions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_burn_completions" ON burn_completions;
CREATE POLICY "own_burn_completions" ON burn_completions
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- weight_entries
-- ==================================================================

CREATE TABLE IF NOT EXISTS weight_entries (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE weight_entries ADD COLUMN for_date text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'weight_entries'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE weight_entries ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_weight_entries_user ON weight_entries (user_id);
CREATE INDEX IF NOT EXISTS idx_weight_entries_updated ON weight_entries (updated_at);

-- The push upserts on this pair, so it must be unique.
DO $$ BEGIN
  ALTER TABLE weight_entries ADD CONSTRAINT weight_entries_user_date_key
    UNIQUE (user_id, for_date);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

ALTER TABLE weight_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_weight_entries" ON weight_entries;
CREATE POLICY "own_weight_entries" ON weight_entries
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- food_catalog
-- ==================================================================

CREATE TABLE IF NOT EXISTS food_catalog (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE food_catalog ADD COLUMN name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN name_ur text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN portion_label text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN grams integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN kcal_min integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN kcal_max integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN image_url text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN is_verified boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'food_catalog'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE food_catalog ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_food_catalog_user ON food_catalog (user_id);
CREATE INDEX IF NOT EXISTS idx_food_catalog_updated ON food_catalog (updated_at);

ALTER TABLE food_catalog ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_food_catalog" ON food_catalog;
CREATE POLICY "own_food_catalog" ON food_catalog
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- program_completions
-- ==================================================================

CREATE TABLE IF NOT EXISTS program_completions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE program_completions ADD COLUMN program_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN week_number integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN day_number integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN completed_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'program_completions'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE program_completions ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_program_completions_user ON program_completions (user_id);
CREATE INDEX IF NOT EXISTS idx_program_completions_updated ON program_completions (updated_at);

ALTER TABLE program_completions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_program_completions" ON program_completions;
CREATE POLICY "own_program_completions" ON program_completions
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- notification_prefs
-- ==================================================================

CREATE TABLE IF NOT EXISTS notification_prefs (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  user_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE notification_prefs ADD COLUMN meal_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN meal_times text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN streak_risk_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN milestones_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN global_mute boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN burn_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN program_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_day integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_time text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN water_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_hours_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_from text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_to text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- A singleton row is keyed by the owner, so id IS user_id.
UPDATE notification_prefs SET user_id = id WHERE user_id IS NULL;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notification_prefs'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE notification_prefs ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_notification_prefs_updated ON notification_prefs (updated_at);

ALTER TABLE notification_prefs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_notification_prefs" ON notification_prefs;
CREATE POLICY "own_notification_prefs" ON notification_prefs
  FOR ALL USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ==================================================================
-- chat_conversations
-- ==================================================================

CREATE TABLE IF NOT EXISTS chat_conversations (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE chat_conversations ADD COLUMN title text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'chat_conversations'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE chat_conversations ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user ON chat_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversations_updated ON chat_conversations (updated_at);

ALTER TABLE chat_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_chat_conversations" ON chat_conversations;
CREATE POLICY "own_chat_conversations" ON chat_conversations
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- chat_messages
-- ==================================================================

CREATE TABLE IF NOT EXISTS chat_messages (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE chat_messages ADD COLUMN conversation_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN role text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN content text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'chat_messages'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE chat_messages ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_chat_messages_user ON chat_messages (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_updated ON chat_messages (updated_at);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_chat_messages" ON chat_messages;
CREATE POLICY "own_chat_messages" ON chat_messages
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- machine_scans
-- ==================================================================

CREATE TABLE IF NOT EXISTS machine_scans (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE machine_scans ADD COLUMN machine_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN response_json text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'machine_scans'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE machine_scans ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_machine_scans_user ON machine_scans (user_id);
CREATE INDEX IF NOT EXISTS idx_machine_scans_updated ON machine_scans (updated_at);

ALTER TABLE machine_scans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_machine_scans" ON machine_scans;
CREATE POLICY "own_machine_scans" ON machine_scans
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- notifications
-- ==================================================================

CREATE TABLE IF NOT EXISTS notifications (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE notifications ADD COLUMN category text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN title text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN body text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN payload text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN read_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notifications'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE notifications ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_updated ON notifications (updated_at);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_notifications" ON notifications;
CREATE POLICY "own_notifications" ON notifications
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- saved_products
-- ==================================================================

CREATE TABLE IF NOT EXISTS saved_products (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE saved_products ADD COLUMN quantity real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'saved_products'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE saved_products ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_saved_products_user ON saved_products (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_products_updated ON saved_products (updated_at);

ALTER TABLE saved_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_saved_products" ON saved_products;
CREATE POLICY "own_saved_products" ON saved_products
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- Verify: every synced table should appear, with rls_enabled = true.
-- ==================================================================
SELECT c.relname AS table_name, c.relrowsecurity AS rls_enabled
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relname IN (
  'profiles',
  'food_logs',
  'burn_completions',
  'weight_entries',
  'food_catalog',
  'program_completions',
  'notification_prefs',
  'chat_conversations',
  'chat_messages',
  'machine_scans',
  'notifications',
  'saved_products'
) ORDER BY c.relname;

