-- FitPilot — Supabase schema
-- GENERATED by tool/generate_supabase_sql.dart. Do not hand-edit:
-- regenerate after changing lib/data/sync/sync_tables.dart.
--
-- Safe to re-run. Creates what is missing, adds columns that are
-- absent, and never drops a table or a column that holds data.

-- ==================================================================
-- profiles
-- ==================================================================

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  user_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE profiles ADD COLUMN name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN avatar_url text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN goal_weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN height_cm real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN age integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN gender text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN goal text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN activity_level text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN allowance_kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN target_override integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN equipment text[]; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN theme_mode text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN theme_color text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN plan_category_pref text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN plan_pace_pref text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN unit_kg_lb text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN week_starts_mon boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN haptics_on boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_week integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN active_program_day integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN onboarding_complete boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE profiles ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- A singleton row is keyed by the owner, so id IS user_id.
UPDATE profiles SET user_id = id WHERE user_id IS NULL;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('name', 'text'),
    ('avatar_url', 'text'),
    ('weight_kg', 'real'),
    ('goal_weight_kg', 'real'),
    ('height_cm', 'real'),
    ('age', 'integer'),
    ('gender', 'text'),
    ('goal', 'text'),
    ('activity_level', 'text'),
    ('allowance_kcal', 'integer'),
    ('target_override', 'integer'),
    ('theme_mode', 'text'),
    ('theme_color', 'text'),
    ('plan_category_pref', 'text'),
    ('plan_pace_pref', 'text'),
    ('unit_kg_lb', 'text'),
    ('week_starts_mon', 'boolean'),
    ('haptics_on', 'boolean'),
    ('active_program_id', 'text'),
    ('active_program_week', 'integer'),
    ('active_program_day', 'integer'),
    ('onboarding_complete', 'boolean'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'profiles'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE profiles ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'profiles.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'profiles.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;
DO $do$
DECLARE have text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod) INTO have
  FROM pg_attribute a
  WHERE a.attrelid = 'profiles'::regclass AND a.attname = 'equipment'
    AND a.attnum > 0 AND NOT a.attisdropped;
  IF have IS NOT NULL AND have <> 'text[]' THEN
    ALTER TABLE profiles ALTER COLUMN equipment TYPE text[]
      USING CASE
        WHEN equipment IS NULL
          OR btrim(equipment::text) IN ('', '[]') THEN '{}'::text[]
        ELSE translate(equipment::text, '[]"', '')::text[]
      END;
    RAISE NOTICE 'profiles.equipment: % -> text[]', have;
  END IF;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'profiles'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE profiles DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'profiles: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE profiles ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_profiles_updated ON profiles (updated_at);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_profiles" ON profiles;
CREATE POLICY "own_profiles" ON profiles
  FOR ALL USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ==================================================================
-- food_logs
-- ==================================================================

CREATE TABLE IF NOT EXISTS food_logs (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE food_logs ADD COLUMN food_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN food_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN custom_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN quantity real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN kcal_min integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN kcal_max integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN source text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN logged_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN deleted_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_logs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('food_id', 'text'),
    ('food_name', 'text'),
    ('custom_name', 'text'),
    ('quantity', 'real'),
    ('kcal_min', 'integer'),
    ('kcal_max', 'integer'),
    ('source', 'text'),
    ('logged_at', 'text'),
    ('deleted_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'food_logs'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE food_logs ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'food_logs.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'food_logs.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'food_logs'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE food_logs DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'food_logs: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'food_logs'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE food_logs ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_food_logs_user ON food_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_food_logs_updated ON food_logs (updated_at);

ALTER TABLE food_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_food_logs" ON food_logs;
CREATE POLICY "own_food_logs" ON food_logs
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- burn_completions
-- ==================================================================

CREATE TABLE IF NOT EXISTS burn_completions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE burn_completions ADD COLUMN for_date text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN activity text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN minutes integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN completed_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE burn_completions ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('for_date', 'text'),
    ('activity', 'text'),
    ('minutes', 'integer'),
    ('kcal', 'integer'),
    ('completed_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'burn_completions'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE burn_completions ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'burn_completions.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'burn_completions.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'burn_completions'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE burn_completions DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'burn_completions: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'burn_completions'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE burn_completions ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_burn_completions_user ON burn_completions (user_id);
CREATE INDEX IF NOT EXISTS idx_burn_completions_updated ON burn_completions (updated_at);

ALTER TABLE burn_completions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_burn_completions" ON burn_completions;
CREATE POLICY "own_burn_completions" ON burn_completions
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- weight_entries
-- ==================================================================

CREATE TABLE IF NOT EXISTS weight_entries (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE weight_entries ADD COLUMN for_date text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN weight_kg real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE weight_entries ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('for_date', 'text'),
    ('weight_kg', 'real'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'weight_entries'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE weight_entries ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'weight_entries.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'weight_entries.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'weight_entries'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE weight_entries DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'weight_entries: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'weight_entries'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE weight_entries ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_weight_entries_user ON weight_entries (user_id);
CREATE INDEX IF NOT EXISTS idx_weight_entries_updated ON weight_entries (updated_at);

-- The push upserts on this pair, so it must be unique.
DO $$ BEGIN
  ALTER TABLE weight_entries ADD CONSTRAINT weight_entries_user_date_key
    UNIQUE (user_id, for_date);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

ALTER TABLE weight_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_weight_entries" ON weight_entries;
CREATE POLICY "own_weight_entries" ON weight_entries
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- food_catalog
-- ==================================================================

CREATE TABLE IF NOT EXISTS food_catalog (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE food_catalog ADD COLUMN name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN name_ur text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN portion_label text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN grams integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN kcal_min integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN kcal_max integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN image_url text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN is_verified boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE food_catalog ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('name', 'text'),
    ('name_ur', 'text'),
    ('portion_label', 'text'),
    ('grams', 'integer'),
    ('kcal_min', 'integer'),
    ('kcal_max', 'integer'),
    ('image_url', 'text'),
    ('is_verified', 'boolean'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'food_catalog'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE food_catalog ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'food_catalog.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'food_catalog.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'food_catalog'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE food_catalog DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'food_catalog: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'food_catalog'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE food_catalog ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_food_catalog_user ON food_catalog (user_id);
CREATE INDEX IF NOT EXISTS idx_food_catalog_updated ON food_catalog (updated_at);

ALTER TABLE food_catalog ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_food_catalog" ON food_catalog;
CREATE POLICY "own_food_catalog" ON food_catalog
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- program_completions
-- ==================================================================

CREATE TABLE IF NOT EXISTS program_completions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE program_completions ADD COLUMN program_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN week_number integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN day_number integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN kcal integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN completed_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE program_completions ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('program_id', 'text'),
    ('week_number', 'integer'),
    ('day_number', 'integer'),
    ('kcal', 'integer'),
    ('completed_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'program_completions'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE program_completions ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'program_completions.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'program_completions.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'program_completions'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE program_completions DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'program_completions: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'program_completions'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE program_completions ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_program_completions_user ON program_completions (user_id);
CREATE INDEX IF NOT EXISTS idx_program_completions_updated ON program_completions (updated_at);

ALTER TABLE program_completions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_program_completions" ON program_completions;
CREATE POLICY "own_program_completions" ON program_completions
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- notification_prefs
-- ==================================================================

CREATE TABLE IF NOT EXISTS notification_prefs (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  user_id uuid,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE notification_prefs ADD COLUMN meal_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN meal_times text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN streak_risk_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN milestones_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN global_mute boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN burn_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN program_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_day integer; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN weigh_in_time text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN water_reminders_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_hours_enabled boolean; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_from text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN quiet_to text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notification_prefs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- A singleton row is keyed by the owner, so id IS user_id.
UPDATE notification_prefs SET user_id = id WHERE user_id IS NULL;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('meal_reminders_enabled', 'boolean'),
    ('meal_times', 'text'),
    ('streak_risk_enabled', 'boolean'),
    ('milestones_enabled', 'boolean'),
    ('global_mute', 'boolean'),
    ('burn_reminders_enabled', 'boolean'),
    ('program_reminders_enabled', 'boolean'),
    ('weigh_in_enabled', 'boolean'),
    ('weigh_in_day', 'integer'),
    ('weigh_in_time', 'text'),
    ('water_reminders_enabled', 'boolean'),
    ('quiet_hours_enabled', 'boolean'),
    ('quiet_from', 'text'),
    ('quiet_to', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'notification_prefs'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE notification_prefs ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'notification_prefs.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'notification_prefs.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'notification_prefs'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE notification_prefs DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'notification_prefs: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notification_prefs'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE notification_prefs ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_notification_prefs_updated ON notification_prefs (updated_at);

ALTER TABLE notification_prefs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_notification_prefs" ON notification_prefs;
CREATE POLICY "own_notification_prefs" ON notification_prefs
  FOR ALL USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ==================================================================
-- chat_conversations
-- ==================================================================

CREATE TABLE IF NOT EXISTS chat_conversations (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE chat_conversations ADD COLUMN title text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_conversations ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('title', 'text'),
    ('created_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'chat_conversations'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE chat_conversations ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'chat_conversations.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'chat_conversations.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'chat_conversations'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE chat_conversations DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'chat_conversations: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'chat_conversations'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE chat_conversations ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user ON chat_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversations_updated ON chat_conversations (updated_at);

ALTER TABLE chat_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_chat_conversations" ON chat_conversations;
CREATE POLICY "own_chat_conversations" ON chat_conversations
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- chat_messages
-- ==================================================================

CREATE TABLE IF NOT EXISTS chat_messages (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE chat_messages ADD COLUMN conversation_id text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN role text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN content text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE chat_messages ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('conversation_id', 'text'),
    ('role', 'text'),
    ('content', 'text'),
    ('created_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'chat_messages'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE chat_messages ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'chat_messages.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'chat_messages.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'chat_messages'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE chat_messages DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'chat_messages: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'chat_messages'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE chat_messages ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_chat_messages_user ON chat_messages (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_updated ON chat_messages (updated_at);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_chat_messages" ON chat_messages;
CREATE POLICY "own_chat_messages" ON chat_messages
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- machine_scans
-- ==================================================================

CREATE TABLE IF NOT EXISTS machine_scans (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE machine_scans ADD COLUMN machine_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN response_json text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE machine_scans ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('machine_name', 'text'),
    ('response_json', 'text'),
    ('created_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'machine_scans'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE machine_scans ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'machine_scans.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'machine_scans.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'machine_scans'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE machine_scans DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'machine_scans: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'machine_scans'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE machine_scans ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_machine_scans_user ON machine_scans (user_id);
CREATE INDEX IF NOT EXISTS idx_machine_scans_updated ON machine_scans (updated_at);

ALTER TABLE machine_scans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_machine_scans" ON machine_scans;
CREATE POLICY "own_machine_scans" ON machine_scans
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- notifications
-- ==================================================================

CREATE TABLE IF NOT EXISTS notifications (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE notifications ADD COLUMN category text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN title text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN body text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN payload text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN created_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN read_at text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE notifications ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('category', 'text'),
    ('title', 'text'),
    ('body', 'text'),
    ('payload', 'text'),
    ('created_at', 'text'),
    ('read_at', 'text'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'notifications'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE notifications ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'notifications.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'notifications.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'notifications'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE notifications DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'notifications: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notifications'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE notifications ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_updated ON notifications (updated_at);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_notifications" ON notifications;
CREATE POLICY "own_notifications" ON notifications
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- saved_products
-- ==================================================================

CREATE TABLE IF NOT EXISTS saved_products (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  BEGIN ALTER TABLE saved_products ADD COLUMN quantity real; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN deleted boolean NOT NULL DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN user_id uuid; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE saved_products ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(); EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- Coerce legacy column types in place (data is preserved).
DO $do$
DECLARE
  want record;
  have text;
BEGIN
  FOR want IN SELECT * FROM (VALUES
    ('quantity', 'real'),
    ('updated_at', 'timestamp with time zone')
  ) AS t(col, typ) LOOP
    SELECT format_type(a.atttypid, a.atttypmod) INTO have
    FROM pg_attribute a
    WHERE a.attrelid = 'saved_products'::regclass
      AND a.attname = want.col AND a.attnum > 0 AND NOT a.attisdropped;
    CONTINUE WHEN have IS NULL OR have = want.typ;
    BEGIN
      EXECUTE format(
        'ALTER TABLE saved_products ALTER COLUMN %I TYPE %s USING %I::text::%s',
        want.col, want.typ, want.col, want.typ);
      RAISE NOTICE 'saved_products.%: % -> %', want.col, have, want.typ;
    EXCEPTION WHEN others THEN
      -- Reported, not fatal. One stubborn column must not abort the migration
      -- for every table after it.
      RAISE WARNING 'saved_products.% could not become % (currently %): %',
        want.col, want.typ, have, SQLERRM;
    END;
  END LOOP;
END $do$;

-- Drop legacy FKs that impose an insert order the sync cannot guarantee.
DO $do$
DECLARE fk record;
BEGIN
  FOR fk IN
    SELECT conname, confrelid::regclass::text AS target
    FROM pg_constraint
    WHERE conrelid = 'saved_products'::regclass AND contype = 'f'
  LOOP
    CONTINUE WHEN fk.target IN ('users', 'auth.users');
    EXECUTE format('ALTER TABLE saved_products DROP CONSTRAINT %I', fk.conname);
    RAISE NOTICE 'saved_products: dropped FK % -> %', fk.conname, fk.target;
  END LOOP;
END $do$;

-- Drop legacy NOT NULLs: the app saves partial rows during
-- onboarding and would otherwise be rejected.
DO $$
DECLARE col record;
BEGIN
  FOR col IN
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'saved_products'
      AND is_nullable = 'NO'
      AND column_name NOT IN ('id', 'user_id', 'updated_at', 'deleted')
  LOOP
    EXECUTE format('ALTER TABLE saved_products ALTER COLUMN %I DROP NOT NULL', col.column_name);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_saved_products_user ON saved_products (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_products_updated ON saved_products (updated_at);

ALTER TABLE saved_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "own_saved_products" ON saved_products;
CREATE POLICY "own_saved_products" ON saved_products
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==================================================================
-- Verify: every synced table should appear, with rls_enabled = true.
-- ==================================================================
SELECT c.relname AS table_name, c.relrowsecurity AS rls_enabled
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relname IN (
  'profiles',
  'food_logs',
  'burn_completions',
  'weight_entries',
  'food_catalog',
  'program_completions',
  'notification_prefs',
  'chat_conversations',
  'chat_messages',
  'machine_scans',
  'notifications',
  'saved_products'
) ORDER BY c.relname;

